config/routes.rb
Rails.application.routes.draw do
  
  mount Payola::Engine => '/payola', as: :payola
  
  root 'pages#home'
  get "dashboard" => "pages#dashboard"
  get "mybusiness" => "pages#mybusiness"
  get "myclients" => "pages#myclients"
  get "myschedule" => "pages#myschedule"
  get "advertising" => "pages#advertising"
  get "reports" => "pages#reports"
  get "pricing" => "pages#pricing"
  
  
  devise_for :users
  get "user_setup_complete" => "pages#user_setup_complete"
  
  resources :businesses, :payment_terms, except: [:index]
  resources :invoicing_line_items, except: [:index, :show, :edit, :new]
  resources :services, :enrollments, :bills, :subscriptions
  
  resources :clients do
    member do
      get :confirm_email
    end
  end
  
  post 'enroll' => 'enrollments#add_enrollment'
  get 'enroll' => 'enrollments#add_enrollment'
  
  resources :jobs, except: [:show] do
    put :sort, on: :collection
  end
  get "itinerary" => "jobs#itinerary"
  
  

  
  get 'resend_confirmation' => 'pages#resend_confirmation' # user confirmation
  get 'resend_client_confirmation' => 'clients#resend_client_confirmation'

end

app/models/service.rb
class Service < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :business
  has_one :enrollment, dependent: :restrict_with_error
  has_many :clients, through: :enrollment, dependent: :restrict_with_error

  validates :name, :description, :price, :business_id, presence: true

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_business

  respond_to :html

  def index
    @services = Service.where("business_id = ?", current_user.business.id).order(name: :asc)
    respond_with(@services)
  end

  def show
    respond_with(@service)
  end

  def new
    @service = current_user.business.services.new
    respond_with(@service)
  end

  def edit
  end

  def create
    @service = current_user.business.services.new(service_params)
    if @service.save
      flash[:success] = 'Service was successfully created.'
      respond_with @service
    else
      render action: 'new'
    end
  end

  def update
    if @service.update(service_params)
      flash[:success] = 'Service changes were successfully saved.'
      respond_with(@service)
    else
      render action: 'edit'
    end
  end

  def destroy
    if @service.destroy
      flash[:notice] = 'Service was successfully deleted.'
      redirect_to mybusiness_path
    else
      flash[:alert] = 'The service could not be deleted, probably because there are already enrollments and/or jobs associated with it.'
      redirect_to request.referrer
    end
  end

  private
    def set_service
      @service = Service.find(params[:id])
    end

    def correct_user
      @service = current_user.business.services.find_by(id: params[:id])
      if @service.nil?
        flash[:error] = "You are not authorized for that service."
        redirect_to services_path
      end
    end

    def service_params
      params.require(:service).permit(:name, :description, :price)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="well">
      <%= simple_form_for(@service) do |f| %>
        <% if @service.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

            <ul>
            <% @service.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-inputs">
          <%= f.input :name %>
          <%= f.input :description %>
          <%= f.label :price %>
          <div class="input-group">
            <span class="input-group-addon">$</span>
            <%= f.input :price, value: number_with_precision(f.object.price, precision: 2), label: false  %>
          </div>
          <br>
        </div>
      
        <div class="form-actions">
          <%= button_tag :submit, class: "btn btn-primary", "data-disable-with" => "Saving..." do %>
            <i class="fa fa-save"></i> Save
          <% end %>
          <%= link_to :back, class: "btn btn-link", "data-no-turbolink" => true do %>
            <i class="fa fa-times"></i> Cancel
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-md-8"></div>
</div>

app/views/services/_services.html.erb
<h3>Services I Offer</h3>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price/Hr</th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td>
          <%= link_to service, class: "btn btn-link btn-xs", "data-no-turbolink" => true, "data-toggle" => "tooltip", "data-placement" => "top", title: "View Service" do %>
            <i class="fa fa-search"></i> <%= service.name %>
          <% end %>
        </td>
        <td><%= service.description %></td>
        <td><%= number_to_currency service.price %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to new_service_path, class: "btn btn-default", "data-toggle" => "tooltip", "data-placement" => "top", title: "New Service" do %>
  <i class="fa fa-plus"></i> New Service
<% end %>

app/views/services/edit.html.erb
<h4>Edit Service</h4>
<%= render 'form' %>

app/views/services/index.html.erb
<%= render "services" %>

app/views/services/new.html.erb
<h4>New Service</h4>
<%= render 'form' %>

app/views/services/show.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @service.name %></h3>
      </div>
      <div class="panel-body">
        <p>
          <strong>Description:</strong>
          <%= @service.description %>
        </p>
        <p>
          <strong>Price:</strong>
          <%= number_to_currency @service.price %>
        </p>
      </div>
      <div class="panel-footer">
        <%= link_to edit_service_path(@service), class: "btn btn-default" do %>
          <i class="fa fa-pencil-square-o"></i> Edit
        <% end %>
        <%= link_to @service, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link", "data-toggle" => "tooltip", "data-placement" => "top", title: "Delete Service" do %>
          <i class="fa fa-trash"></i> Delete
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-8"></div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Clients</h3>
  </div>
  <div class="panel-body">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Client</th>
          <th>Enrolled?</th>
          <th class="hidden-xs">As Of</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @clients = current_user.business.clients.all %>
        <% if @clients.count > 0 %>
          <% @clients.each do |c| %>
            <tr>
              <td><%= link_to c.full_name, c, "data-no-turbolink" => true %></td>
              <% @enrollment = Enrollment.where(client_id: c.id, service_id: @service.id, deleted_at: nil).last %>
              <% if @enrollment.nil? %>
                <td>
                  <%= link_to enroll_path(client_id: c.id, service_id: @service.id), class: '' do %>
                    <span data-toggle="tooltip" data-placement="top" title="Enroll <%= c.full_name %>"><i class="fa fa-square-o fa-lg"></i> No</span>
                  <% end %>
                </td>
                <td class="hidden-xs"></td>
                <td></td>
              <% else %>
                <td>
                  <%= link_to enrollment_path(id: @enrollment, service_id: @service.id), method: :delete, data: { confirm: 'Are you sure?' }, class: '' do %>
                    <span data-toggle="tooltip" data-placement="top" title="Unenroll <%= c.full_name %>"><i class="fa fa-check-square-o fa-lg"></i> Yes</span>
                  <% end %>
                </td>
                <td class="hidden-xs"><%= l @enrollment.created_at, day: @enrollment.created_at.day.ordinalize, format: :full_date %></td>
                <td><a href="#details_<%= c.id %>" data-toggle="collapse" data-target="#details_<%= c.id %>">Details...</a></td>
              <% end %>
            </tr>
            <tr>
              <td colspan="4" class="hidden-row">
                <div class="collapse panel-body" id="details_<%= c.id %>">
                  <p>Preferences for <%= c.full_name %>: <%= render 'enrollments/form', enrollment: @enrollment %></p>
                  <p><%= c.full_name %> schedule:<%= render 'enrollments/schedule', enrollment: @enrollment %></p>
                </div>
              </td>
            </tr>
          <% end %>
        <% else %>
          <tr>
            <td>You haven't created any clients yet. <%= link_to 'Go set up some clients...', clients_path %></td>
            <td></td>
            <td class="hidden-xs"></td>
            <td></td>
          </tr>
        <% end %>
      <tbody>
    </table>
  </div>
</div>