config/routes.rb
Rails.application.routes.draw do
  
  mount Payola::Engine => '/payola', as: :payola
  
  root 'pages#home'
  get "dashboard" => "pages#dashboard"
  get "mybusiness" => "pages#mybusiness"
  get "myclients" => "pages#myclients"
  get "myschedule" => "pages#myschedule"
  get "advertising" => "pages#advertising"
  get "reports" => "pages#reports"
  get "pricing" => "pages#pricing"
  
  
  devise_for :users
  get "user_setup_complete" => "pages#user_setup_complete"
  
  resources :businesses, :payment_terms, except: [:index]
  resources :invoicing_line_items, except: [:index, :show, :edit, :new]
  resources :services, :enrollments, :bills, :subscriptions
  
  resources :clients do
    member do
      get :confirm_email
    end
  end
  
  post 'enroll' => 'enrollments#add_enrollment'
  get 'enroll' => 'enrollments#add_enrollment'
  
  resources :jobs, except: [:show] do
    put :sort, on: :collection
  end
  get "itinerary" => "jobs#itinerary"
  
  

  
  get 'resend_confirmation' => 'pages#resend_confirmation' # user confirmation
  get 'resend_client_confirmation' => 'clients#resend_client_confirmation'

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  respond_to :html

#   def index
#     @businesses = Business.where("id = ?", current_user.business.id)
#     respond_with(@businesses)
#   end

  def show
    respond_with(@business)
  end

  def new
    @business = current_user.build_business
    respond_with(@business)
  end

  def edit
  end
  
  def create
    @business = current_user.build_business(business_params)
    if @business.save
      flash[:success] = 'Your business profile has been created.'
      redirect_to mybusiness_path
    else
      render action: 'new'
    end
  end

  def update
    if @business.update(business_params)
      flash[:success] = 'Your business profile changes were saved.'
      redirect_to mybusiness_path
    else
      render action: 'edit'
    end
  end

  def destroy
    @business.destroy
    flash[:notice] = 'Your business profile was deleted.'
    redirect_to mybusiness_path
  end

  private
    def set_business
      @business = current_user.business
    end
  
    def correct_user
      unless params[:id].to_i == current_user.business.id
        flash[:error] = "You are not authorized for that business profile."
        redirect_to mybusiness_path
      end
    end

    def business_params
      params.require(:business).permit(:name, :contact_name, :about, :addr1, :addr2, :city, :state, :postal_code, :country, :phone)
    end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_business.html.erb
<h3>My Business Profile</h3>
<div class="well">
  <p>
    <strong>Name:</strong>
    <%= @business.name %>
  </p>
  <p>
    <strong>About:</strong>
    <%= @business.about %>
  </p>
  <p>
    <strong>Contact Name:</strong>
    <%= @business.contact_name %>
  </p>
  <address>
    <strong>Address</strong><br>
    <%= @business.addr1 %><br>
    <%= @business.addr2 %><% unless @business.addr2.blank? %><br><% end %>
    <%= @business.city %>, <%= @business.state %> <%= @business.postal_code %><br>
    <%= @business.country %>
  </address>
  <p>
    <strong>Phone:</strong>
    <%= @business.phone %>
  </p>
  <%= link_to edit_business_path(@business), class: "btn btn-default" do %>
    <i class="fa fa-pencil-square-o"></i> Edit
  <% end %>
</div>

app/views/businesses/_form.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="well">
    <%= simple_form_for(@business) do |f| %>
      <% if @business.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@business.errors.count, "error") %> prohibited this business from being saved:</h2>

          <ul>
          <% @business.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-inputs">
        <%= f.input :name %>
        <%= f.input :contact_name %>
        <%= f.input :about %>
        <%= f.input :addr1 %>
        <%= f.input :addr2 %>
        <%= f.input :city %>
        <%= f.input :state, collection: us_states_and_ca_provinces %>
        <%= f.input :postal_code %>
        <%= f.input :country %>
        <%= f.input :phone %>
      </div>

      <div class="form-actions">
        <%= button_tag :submit, class: "btn btn-primary", "data-disable-with" => "Saving..." do %>
          <i class="fa fa-save"></i> Save
        <% end %>
        <%= link_to :back, class: "btn btn-link" do %>
          <i class="fa fa-times"></i> Cancel
        <% end %>
      </div>
    <% end %>
    </div>
  </div>
  <div class="col-md-8"></div>
</div>

app/views/businesses/edit.html.erb
<h4>My Business Profile</h4>
<%= render 'form' %>

app/views/businesses/new.html.erb
<h4>My Business Profile</h4>
<%= render 'form' %>

app/views/businesses/show.html.erb
<div class="row">
  <div class="col-md-4">
    <%= render "business" %>
  </div>
  <div class="col-md-8"></div>
</div>