config/routes.rb
Rails.application.routes.draw do
  
  mount Payola::Engine => '/payola', as: :payola
  
  root 'pages#home'
  get "dashboard" => "pages#dashboard"
  get "mybusiness" => "pages#mybusiness"
  get "myclients" => "pages#myclients"
  get "myschedule" => "pages#myschedule"
  get "advertising" => "pages#advertising"
  get "reports" => "pages#reports"
  get "pricing" => "pages#pricing"
  
  
  devise_for :users
  get "user_setup_complete" => "pages#user_setup_complete"
  
  resources :businesses, :payment_terms, except: [:index]
  resources :invoicing_line_items, except: [:index, :show, :edit, :new]
  resources :services, :enrollments, :bills, :subscriptions
  
  resources :clients do
    member do
      get :confirm_email
    end
  end
  
  post 'enroll' => 'enrollments#add_enrollment'
  get 'enroll' => 'enrollments#add_enrollment'
  
  resources :jobs, except: [:show] do
    put :sort, on: :collection
  end
  get "itinerary" => "jobs#itinerary"
  
  

  
  get 'resend_confirmation' => 'pages#resend_confirmation' # user confirmation
  get 'resend_client_confirmation' => 'clients#resend_client_confirmation'

end

app/models/payment_term.rb
class PaymentTerm < ActiveRecord::Base
  #acts_as_paranoid
  
  has_one :business
  
  validates :days_to_pay, :business_id, presence: true
end

app/controllers/payment_terms_controller.rb
class PaymentTermsController < ApplicationController
  before_action :set_payment_term, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_business

  respond_to :html

#   def index
#     @payment_terms = PaymentTerm.where("business_id = ?", current_user.business.id)
#     respond_with(@payment_terms)
#   end

  def show
    respond_with(@payment_term)
  end

  def new
    @payment_term = PaymentTerm.new
    respond_with(@payment_term)
  end

  def edit
  end

  def create
    @payment_term = PaymentTerm.new(payment_term_params)
    if @payment_term.save
      flash[:success] = 'Payment terms were successfully created.'
      redirect_to mybusiness_path
    else
      render action: 'new'
    end
  end

  def update
    if @payment_term.update(payment_term_params)
      flash[:success] = 'Payment terms changes were successfully saved.'
      redirect_to mybusiness_path
    else
      render action: 'edit'
    end
  end

  def destroy
    @payment_term.destroy
    flash[:notice] = 'Payment terms were successfully deleted.'
    redirect_to mybusiness_path
  end

  private
    def set_payment_term
      @payment_term = PaymentTerm.find(params[:id])
    end
  
    def correct_user
      unless params[:id].to_i == current_user.business.payment_term.id
        flash[:error] = "You are not authorized for those payment terms."
        redirect_to mybusiness_path
      end
    end
  
    def payment_term_params
      params.require(:payment_term).permit(:days_to_pay, :business_id)
    end
end

app/helpers/payment_terms_helper.rb
module PaymentTermsHelper
end

app/views/payment_terms/_form.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="well">
      <%= simple_form_for(@payment_term) do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">
          <%= f.input :days_to_pay %>
          <%= f.hidden_field :business_id, value: current_user.business.id %>
        </div>

        <div class="form-actions">
          <%= button_tag :submit, class: "btn btn-primary", "data-disable-with" => "Saving..." do %>
            <i class="fa fa-save"></i> Save
          <% end %>
          <%= link_to :back, class: "btn btn-link" do %>
            <i class="fa fa-times"></i> Cancel
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="well">
      <h5><i class="fa fa-lightbulb-o fa-lg"></i> <strong>Quick Tip:</strong></h5> This is the number of days your clients have to pay each bill before it is considered late.
    </div>
  </div>
  <div class="col-md-8"></div>
</div>

app/views/payment_terms/_payment_terms.html.erb
<h3>My Payment Terms</h3>
<div class="well">
  <p>
    <strong>Days To Pay:</strong>
    <%= @payment_term.days_to_pay %>
  </p>
  <%= link_to edit_payment_term_path(@payment_term), class: "btn btn-default" do %>
    <i class="fa fa-pencil-square-o"></i> Edit
  <% end %>
</div>

app/views/payment_terms/edit.html.erb
<h4>My Payment Terms</h4>
<%= render 'form' %>

app/views/payment_terms/new.html.erb
<h4>My Payment Terms</h4>
<%= render 'form' %>

app/views/payment_terms/show.html.erb
<div class="row">
  <div class="col-md-4">
    <%= render "payment_terms" %>
    <div class="well">
      <h5><i class="fa fa-lightbulb-o fa-lg"></i> <strong>Quick Tip:</strong></h5> This is the number of days your clients have to pay each bill before it is considered late.
    </div>
  </div>
  <div class="col-md-8">
  </div>
</div>