config/routes.rb
Rails.application.routes.draw do
  
  mount Payola::Engine => '/payola', as: :payola
  
  root 'pages#home'
  get "dashboard" => "pages#dashboard"
  get "mybusiness" => "pages#mybusiness"
  get "myclients" => "pages#myclients"
  get "myschedule" => "pages#myschedule"
  get "advertising" => "pages#advertising"
  get "reports" => "pages#reports"
  get "pricing" => "pages#pricing"
  
  
  devise_for :users
  get "user_setup_complete" => "pages#user_setup_complete"
  
  resources :businesses, :payment_terms, except: [:index]
  resources :invoicing_line_items, except: [:index, :show, :edit, :new]
  resources :services, :enrollments, :bills, :subscriptions
  
  resources :clients do
    member do
      get :confirm_email
    end
  end
  
  post 'enroll' => 'enrollments#add_enrollment'
  get 'enroll' => 'enrollments#add_enrollment'
  
  resources :jobs, except: [:show] do
    put :sort, on: :collection
  end
  get "itinerary" => "jobs#itinerary"
  
  

  
  get 'resend_confirmation' => 'pages#resend_confirmation' # user confirmation
  get 'resend_client_confirmation' => 'clients#resend_client_confirmation'

end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_business
  
  respond_to :html

  def index
    @bills = InvoicingLedgerItem.where(type: 'Bill').where("sender_id = ?", current_user.business.id)
    respond_with(@bills)
  end

  def show
    respond_with(@bill)
  end
  
  def render_html # This uses the gem's built-in HTML for an invoice, but the layout isn't that great, so won't use it in the app.
    bill = InvoicingLedgerItem.where(type: 'Bill').find(params[:format])

    unless bill.sender_id == current_user.id
      raise ActiveRecord::RecordNotFound, "You do not have permission to view this bill."
    end
    
    bill_text = bill.render_html tax_point_column: false, quantity_column: false, tax_amount_column: false, subtotal: false do |i|
      #Show/hide columns by specifying them before: do |i|
        # :tax_point_column
        # :quantity_column
        # :description_column
        # :net_amount_column
        # :tax_amount_column
        # :gross_amount_column
        # :subtotal
      
      #Customize labels:
      #i.date_format "%d %B %Y"
      i.invoice_label "Bill"
      #i.credit_note_label
      i.recipient_label "Customer"
      i.sender_label "Supplier"
      i.tax_number_label "<br />"
      #i.identifier_label
      #i.issue_date_label
      #i.period_start_label
      #i.period_end_label
      #i.due_date_label
      #i.line_tax_point_label
      #i.line_quantity_label
      #i.line_description_label
      i.line_net_amount_label "Price"
      #i.line_tax_amount_label
      #i.line_gross_amount_label
      #i.subtotal_label
      i.total_label "Total Due"
      #i.net_amount_label
      #i.tax_amount_label
      #i.gross_amount_label      
      i.description_tag do |params|
        "<p><strong>Description:</strong> #{params[:description]}</p>\n" +
        "<p>Thank you for your business!</p>\n"
      end
    end
    
    render layout: true, text: bill_text
  end
  
  def create_pdf
    require 'invoicing/ledger_item/pdf_generator'
    bill = InvoicingLedgerItem.where(type: 'Bill').find(params[:format])
    
    pdf_creator = Invoicing::LedgerItem::PdfGenerator.new(bill)
    pdf_file = pdf_creator.render Rails.root.join('/tmp/pdf')
  end
  
#   def send
#     # TODO: Have a mailer which sends bill to client
#     BillMailer.send_bill(@bill).deliver
#     # When it gets sent, set issue_date: Time.zone.now
#   end
  
  def new
    
    @bills = InvoicingLedgerItem.where(type: 'Bill') # Need this so Bill.new will work
    @bill = Bill.new
    #@bill.line_items.build
    #@invoicing_line_item = InvoicingLineItem.new
    
    respond_with(@bill)
  end

  def edit
  end

  def create
    
    # Convert the date formats from Moment.js to Strftime for submission to server
    bill_params_strptime = bill_params
    bill_params_strptime[:period_start] = Date.strptime bill_params_strptime[:period_start], '%m/%d/%Y'
    bill_params_strptime[:period_end] = Date.strptime bill_params_strptime[:period_end], '%m/%d/%Y'
    bill_params_strptime[:due_date] = Date.strptime bill_params_strptime[:due_date], '%m/%d/%Y'
    @bill = Bill.create(bill_params_strptime)
    @bill.sender_id = current_user.business.id
    #@bill.line_items.build(invoicing_line_item_params)
    if @bill.save
      flash[:success] = 'The bill was successfully created for the job.'
      respond_with @bill
    else
      render action: 'new'
    end
  end

  def update
    # Convert the date formats from Moment.js to Strftime for submission to server
    bill_params_strptime = bill_params
    bill_params_strptime[:period_start] = Date.strptime bill_params_strptime[:period_start], '%m/%d/%Y'
    bill_params_strptime[:period_end] = Date.strptime bill_params_strptime[:period_end], '%m/%d/%Y'
    bill_params_strptime[:due_date] = Date.strptime bill_params_strptime[:due_date], '%m/%d/%Y'
    @bill.update(bill_params_strptime)

    respond_with @bill
  end

  def destroy
    @bill.destroy
    #respond_with @bill
    redirect_to myclients_path
  end

  private
    def set_bill
      @bill = InvoicingLedgerItem.where(type: 'Bill').find(params[:id])
      @invoicing_line_items = InvoicingLineItem.where 'ledger_item_id = ?', @bill.id
    end
  
    def correct_user
      @bill = current_user.business.invoicing_ledger_items.find_by(id: params[:id])
      if @bill.nil?
        flash[:error] = "You are not authorized for that bill."
        redirect_to jobs_path
      end
    end

    def bill_params
      params.require(:bill).permit(:sender_id, :recipient_id, :type, :identifier, :issue_date, :currency, :total_amount, :status, :description, :period_start, :period_end, :due_date, :print)
    end
  
end

app/views/bills/_bills.html.erb
<h3>Open Bills <%= link_to "All Bills...", bills_path, class: "btn btn-link" %></h3>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Client</th>
      <th>Bill</th>
      <th>Due Date</th>
      <th>Total Amount</th>
      <th class="hidden-xs">Job</th>
    </tr>
  </thead>

  <tbody>
    <% @bills.where("status = 'open'").each do |bill| %>
      <tr>
        <td><%= bill.recipient.full_name %></td>
        <td>
          <%= link_to bill, class: "btn btn-link btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "View Bill" do %>
            <i class="fa fa-search"></i> <%= bill.identifier %>
          <% end %>
        </td>
        <td><%= l bill.due_date, format: :default_date %></td>
        <td><%= number_to_currency bill.total_amount %></td>
        <td class="hidden-xs"><%= bill.line_items.first.job.short_description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/bills/_form.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="well">
      <%= simple_form_for @bill do |f| %>
        <div class="form-inputs">
          <!--%= f.association :recipient, label_method: :full_name, value_method: :id, prompt: "Choose the recipient (client)" %-->
          <%= f.hidden_field :type, value: "Bill" %>
          <%= f.hidden_field :currency, value: "usd" %>
          <!--%= f.input :identifier %-->
          <!--%= f.input :description %-->
          <% if f.object.new_record? %>
            <!--% ps = "" %-->
            <!--% pe = "" %-->
            <% dd = "" %>
          <% else %>
            <!--% ps = l @bill.period_start, format: :default_date %-->
            <!--% pe = l @bill.period_end, format: :default_date %-->
            <% dd = l @bill.due_date, format: :default_date %>
          <% end %>
          <div class='row datetimerange'>
            <!--%= f.input :period_start, as: :date_picker, wrapper: :ranged_datetime, input_html: { data: { date_options: { defaultDate: ps } }, value: ps } %-->
            <!--%= f.input :period_end, as: :date_picker, wrapper: :ranged_datetime, input_html: { data: { date_options: { defaultDate: pe } }, value: pe } %-->
          </div>
          <%= f.input :due_date, as: :date_picker, input_html: { data: { date_options: { defaultDate: dd } }, value: dd } %>
        </div>
      
        <div class="form-actions">
          <%= button_tag :submit, class: "btn btn-primary", "data-disable-with" => "Saving..." do %>
            <i class="fa fa-save"></i> Save
          <% end %>
          <%= link_to @bill, class: "btn btn-link" do %>
            <i class="fa fa-times"></i> Cancel
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-md-8"></div>
</div>

app/views/bills/_late.html.erb
<h3>Bills Past Due <%= link_to "All Bills...", bills_path, class: "btn btn-link" %></h3>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Client</th>
      <th>Bill</th>
      <th>Due Date</th>
      <th>Total Amount</th>
    </tr>
  </thead>

  
  <tbody>
    <% unless @bills.nil? %>
      <% @bills_past_due = @bills.where("status = 'open' and due_date < ?", Time.zone.now.beginning_of_day) %>
      <% @bills_past_due.each do |bill| %>
        <tr>
          <td><%= bill.recipient.full_name %></td>
          <td>
            <%= link_to bill, class: "btn btn-link btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "View Bill" do %>
              <i class="fa fa-search"></i> <%= bill.identifier %>
            <% end %>
          </td>
          <td><%= l bill.due_date, format: :default_date %></td>
          <td><%= number_to_currency bill.total_amount %></td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="4">There are no late bills right now.</td>
      </tr>
    <% end %>
  </tbody>
  
</table>

<% unless @bills.nil? %>
  <% unless @bills_past_due.any? %>
    There are no past due bills.
  <% end %>
<% end %>

app/views/bills/_today.html.erb
<h3>Bills Due Today <%= link_to "All Bills...", bills_path, class: "btn btn-link" %></h3>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Client</th>
      <th>Bill</th>
      <th>Due Date</th>
      <th>Total Amount</th>
    </tr>
  </thead>

  
  <tbody>
    <% unless @bills.nil? %>
      <% @bills_due_today = @bills.where(due_date: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day, status: 'open') %>
      <% @bills_due_today.each do |bill| %>
      <tr>
        <td><%= bill.recipient.full_name %></td>
        <td>
          <%= link_to bill, class: "btn btn-link btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "View Bill" do %>
            <i class="fa fa-search"></i> <%= bill.identifier %>
          <% end %>
        </td>
        <td><%= l bill.due_date, format: :default_date %></td>
        <td><%= number_to_currency bill.total_amount %></td>
      </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="4">There are no bills due today.</td>
      </tr>
    <% end %>
  </tbody>
</table>

<% unless @bills.nil? %>
  <% unless @bills_due_today.any? %>
    <td>There are no bills due today.</td>
  <% end %>
<% end %>

app/views/bills/edit.html.erb
<h4>Bill <%= @bill.identifier %></h4>
<%= render 'form' %>

app/views/bills/index.html.erb
<h3>Bills</h3>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Client</th>
      <th>Bill</th>
      <th>Status</th>
      <th>Issue Date</th>
      <th>Due Date</th>
      <th>Total Amount</th>
      <th>Job</th>
    </tr>
  </thead>

  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.recipient.full_name %></td>
        <td>
          <%= link_to bill, class: "btn btn-link btn-xs", "data-toggle" => "tooltip", "data-placement" => "top", title: "View Bill" do %>
            <i class="fa fa-search"></i> <%= bill.identifier %>
          <% end %>
        </td>
        <td><%= bill.status %></td>
        <td><%= l bill.issue_date, format: :default_date if bill.issue_date %></td>
        <td><%= l bill.due_date, format: :default_date %></td>
        <td><%= number_to_currency bill.total_amount %></td>
        <td><%= bill.line_items.first.job.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/bills/new.html.erb
<h4>New Bill</h4>
<%= render 'form' %>

app/views/bills/print.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h2 class="panel-title">Bill <%= @bill.identifier %></h2>
  </div>
  <div class="panel-body">
    <p>
      <strong>Receipient:</strong>
      <%= @bill.recipient.full_name %>
    </p>
    <p>
      <strong>Type:</strong>
      <%= @bill.type %>
    </p>
    <p>
      <strong>Issue Date:</strong>
      <%= l @bill.issue_date, format: :default_date if @bill.issue_date %>
    </p>
    <p>
      <strong>Total Amount:</strong>
      <%= number_to_currency @bill.total_amount %>
    </p>
    <p>
      <strong>Status:</strong>
      <%= @bill.status %>
    </p>
    <p>
      <strong>Description:</strong>
      <%= @bill.description %>
    </p>
    <p>
      <strong>Period Start:</strong>
      <%= l @bill.period_start, format: :default_date  %>
    </p>
    <p>
      <strong>Period End:</strong>
      <%= l @bill.period_end, format: :default_date %>
    </p>
    <p>
      <strong>Due Date:</strong>
      <%= l @bill.due_date, format: :default_date %>
    </p>
    
    <hr>
    
    <h4>Details:</h4>
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'invoicing_line_items/list' %>
      </div>  
    </div>
  </div>
</div>

app/views/bills/show.html.erb
<% unless params.has_key?(:print) && params[:print] == 'true' %>
  <%= link_to bill_path(@bill, print: 'true'), class: "btn btn-default hidden-xs", target: "_blank", "data-toggle" => "tooltip", "data-placement" => "right", title: "Open a new window with this bill in a printer-friendly format." do %>
    <i class="fa fa-print"></i> Printer Friendly
  <% end %>
  <hr class="hidden-xs">
<% end %>

<div class="row">
  <div class="col-md-9">
    <address>
      <strong><%= @bill.business_name %></strong><br>
      <%= @bill.business_addr1 %><br>
      <%= @bill.business_addr2 %><% unless @bill.business_addr2.blank? %><br><% end %>
      <%= @bill.business_city %>, <%= @bill.business_state %> <%= @bill.business_postal_code %>
    </address>
  </div>
  <div class="col-md-3">
    <p>
      <strong>Issue Date:</strong>
      <%= l @bill.issue_date, format: :default_date if @bill.issue_date %>
    </p>
    <p>
      <strong>Due Date:</strong>
      <%= l @bill.due_date, format: :default_date %>&nbsp;
      <% unless params.has_key?(:print) && params[:print] == 'true' %>
        <%= link_to edit_bill_path(@bill), "data-toggle" => "tooltip", "data-placement" => "top", title: "Edit Due Date" do %>
          <i class="fa fa-pencil-square-o fa-lg"></i>
        <% end %>
      <% end %>
    </p>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h2 class="panel-title">Bill <%= @bill.identifier %></h2>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-1">
        <h5>Bill To:</h5><br>
      </div>
      <div class="col-md-11">
        <adress>
          <strong><%= @bill.recipient.full_name %></strong><br>
          <%= @bill.client_addr1 %><br>
          <%= @bill.client_addr2 %><% unless @bill.client_addr2.blank? %><br><% end %>
          <%= @bill.client_city %>, <%= @bill.client_state %> <%= @bill.client_postal_code %>
        </adress>
      </div>
    </div>

    <hr>

    <h4>Details:</h4>
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'invoicing_line_items/list' %>
      </div>
      <div class="panel-footer">
        <p class="text-right">
          <span class="h5"><strong>Bill Total: </strong><%= number_to_currency @bill.total_amount %></span>
        </p>
      </div>
    </div>
  </div>
</div>

<% if  params.has_key?(:print) && params[:print] == 'true' %>
  Thank you for your business!
<% end %>